# Generated by Django 5.2.9 on 2026-07-06 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Основной бот", max_length=50),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        db_column="instrument_uid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bot_instrument",
                        to="data.financialinstrument",
                        verbose_name="Финансовый инструмент",
                    ),
                ),
            ],
        ),
    ]
