# Generated by Django 5.2.9 on 2026-05-18 13:49

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("data", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="password"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date joined",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="e-mail"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="«Нельзя использовать пробел и символы, кроме . @ + - _».",
                                regex="^[\\w.@+-]+$",
                            )
                        ],
                        verbose_name="имя пользователя в системе",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь.",
                "verbose_name_plural": "Пользователи.",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="TinkoffAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=50, unique=True)),
                (
                    "access_token",
                    encrypted_fields.fields.EncryptedCharField(max_length=255),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="real_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TinkoffSandboxAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Краткое описание стратегии",
                        max_length=255,
                    ),
                ),
                ("account_id", models.CharField(max_length=50, unique=True)),
                (
                    "access_token",
                    encrypted_fields.fields.EncryptedCharField(max_length=255),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sandbox_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SandboxPostOrderRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.BigIntegerField(help_text="Количество лотов."),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        help_text="Цена за 1 инструмент. Игнорируется для рыночных поручений.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "direction",
                    models.IntegerField(
                        choices=[
                            (0, "Значение не указано"),
                            (1, "Покупка"),
                            (2, "Продажа"),
                        ],
                        help_text="Направление операции (BUY/SELL).",
                    ),
                ),
                (
                    "order_type",
                    models.IntegerField(
                        choices=[
                            (0, "Значение не указано"),
                            (1, "Лимитная"),
                            (2, "Рыночная"),
                            (3, "Лучшая цена"),
                        ],
                        help_text="Тип заявки (LIMIT/MARKET).",
                    ),
                ),
                (
                    "time_in_force",
                    models.IntegerField(
                        choices=[
                            (0, "Значение не определено"),
                            (1, "Заявка действует до конца торгового дня"),
                            (2, "Исполнить или отменить (частично)"),
                            (3, "Исполнить полностью или отменить"),
                        ],
                        default=1,
                        help_text="Алгоритм исполнения поручения (применяется к лимитным).",
                    ),
                ),
                (
                    "price_type",
                    models.IntegerField(
                        choices=[
                            (0, "Значение не определено"),
                            (1, "Цена в пунктах (для фьючерсов и облигаций)"),
                            (2, "Цена в валюте расчетов по инструменту"),
                        ],
                        default=0,
                        help_text="Тип цены.",
                    ),
                ),
                (
                    "confirm_margin_trade",
                    models.BooleanField(
                        default=False,
                        help_text="Согласие на выставление заявки, которая может привести к непокрытой позиции.",
                    ),
                ),
                (
                    "order_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Идентификатор запроса выставления поручения для целей идемпотентности.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="instrument_uid",
                        help_text="Связь с инструментом по instrument_uid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="postorder_by_instrument",
                        to="data.financialinstrument",
                    ),
                ),
                (
                    "account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_order_request",
                        to="user.tinkoffsandboxaccount",
                        to_field="account_id",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поручение",
                "verbose_name_plural": "Поручения",
            },
        ),
        migrations.CreateModel(
            name="SandboxMoney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(max_length=10, verbose_name="валюта"),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=9, default=0, max_digits=20
                    ),
                ),
                (
                    "blocked",
                    models.DecimalField(
                        decimal_places=9, default=0, max_digits=20
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money",
                        to="user.tinkoffsandboxaccount",
                        to_field="account_id",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sandbox Money",
            },
        ),
        migrations.CreateModel(
            name="SandboxPostOrderResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.UUIDField(
                        help_text="Биржевой идентификатор заявки, присвоенный Тинькофф.",
                        unique=True,
                    ),
                ),
                (
                    "order_request_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Идентификатор изначального запроса (UUID для идемпотентности).",
                        null=True,
                    ),
                ),
                (
                    "instrument_uid",
                    models.UUIDField(
                        blank=True,
                        help_text="UID финансового инструмента.",
                        null=True,
                    ),
                ),
                (
                    "figi",
                    models.CharField(
                        blank=True,
                        help_text="FIGI-идентификатор инструмента.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "execution_report_status",
                    models.IntegerField(
                        choices=[
                            (0, "Не определен"),
                            (5, "Исполнен частично"),
                            (1, "Исполнен полностью"),
                            (3, "Отменен"),
                            (4, "Новый / Выставлен"),
                            (2, "Отклонен"),
                        ],
                        default=0,
                        help_text="Текущий статус («стаканного» исполнения) заявки.",
                    ),
                ),
                (
                    "direction",
                    models.IntegerField(
                        choices=[
                            (0, "Значение не указано"),
                            (1, "Покупка"),
                            (2, "Продажа"),
                        ],
                        default=0,
                        help_text="Направление операции.",
                    ),
                ),
                (
                    "order_type",
                    models.IntegerField(
                        choices=[
                            (0, "Значение не указано"),
                            (1, "Лимитная"),
                            (2, "Рыночная"),
                            (3, "Лучшая цена"),
                        ],
                        default=0,
                        help_text="Тип заявки.",
                    ),
                ),
                (
                    "lots_requested",
                    models.BigIntegerField(help_text="Запрошено лотов."),
                ),
                (
                    "lots_executed",
                    models.BigIntegerField(
                        help_text="Фактически исполнено лотов."
                    ),
                ),
                (
                    "initial_order_price",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Начальная цена заявки.",
                        max_digits=18,
                    ),
                ),
                (
                    "executed_order_price",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Средняя цена исполнившихся лотов.",
                        max_digits=18,
                    ),
                ),
                (
                    "total_order_amount",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Общая стоимость по заявке (с комиссией).",
                        max_digits=18,
                    ),
                ),
                (
                    "initial_commission",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Предварительная комиссия.",
                        max_digits=18,
                    ),
                ),
                (
                    "executed_commission",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Фактическая комиссия.",
                        max_digits=18,
                    ),
                ),
                (
                    "aci_value",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Накопленный купонный доход (НКД).",
                        max_digits=18,
                    ),
                ),
                (
                    "initial_security_price",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Начальная цена бумаги.",
                        max_digits=18,
                    ),
                ),
                (
                    "initial_order_price_pt",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Начальная цена заявки в пунктах (для облигаций).",
                        max_digits=18,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Дополнительное сообщение от торговой системы / текст ошибки.",
                    ),
                ),
                (
                    "response_metadata",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Сырые метаданные ответа брокера (tracking_id, server_time).",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Время сохранения ответа в вашу БД.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Время изменения."
                    ),
                ),
                (
                    "order_response",
                    models.OneToOneField(
                        help_text="Ссылка на исходный запрос поручения",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_log",
                        to="user.sandboxpostorderrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на ордер (Песочница)",
                "verbose_name_plural": "Ответы на ордера (Песочница)",
                "indexes": [
                    models.Index(
                        fields=["order_id"],
                        name="user_sandbo_order_i_d0dd98_idx",
                    ),
                    models.Index(
                        fields=["instrument_uid"],
                        name="user_sandbo_instrum_95718c_idx",
                    ),
                    models.Index(
                        fields=["order_request_id"],
                        name="user_sandbo_order_r_8c07bb_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sandboxpostorderrequest",
            index=models.Index(
                fields=["account_id"], name="user_sandbo_account_2b5378_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sandboxpostorderrequest",
            index=models.Index(
                fields=["instrument_id"], name="user_sandbo_instrum_986daa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sandboxmoney",
            index=models.Index(
                fields=["account", "currency"],
                name="user_sandbo_account_7aa588_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sandboxmoney",
            unique_together={("account", "currency")},
        ),
    ]
