# Generated by Django 5.2.9 on 2026-06-14 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TinkoffAccount",
        ),
    ]
