# Generated by Django 5.2.9 on 2026-07-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_delete_tinkoffaccount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sandboxpostorderresponse",
            name="order_response",
        ),
        migrations.DeleteModel(
            name="SandboxPostOrderRequest",
        ),
        migrations.DeleteModel(
            name="SandboxPostOrderResponse",
        ),
    ]
