# Generated by Django 5.2.9 on 2026-06-14 16:39

import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TinkoffAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=50, unique=True)),
                (
                    "access_token",
                    encrypted_fields.fields.EncryptedCharField(
                        help_text="api key токен с доступом к конкретному счету T инвестиции",
                        max_length=255,
                    ),
                ),
                (
                    "access_token_algopack",
                    encrypted_fields.fields.EncryptedCharField(
                        help_text="api key algopack", max_length=1600
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Краткое описание...",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="real_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
