# Generated by Django 5.2.9 on 2026-06-15 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
        ("t_invest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_amount_shares",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Стоимость акций (значение)",
                    ),
                ),
                (
                    "total_amount_bonds",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Стоимость облигаций (значение)",
                    ),
                ),
                (
                    "total_amount_etf",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Стоимость ETF (значение)",
                    ),
                ),
                (
                    "total_amount_currencies",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Стоимость валюты (значение)",
                    ),
                ),
                (
                    "total_amount_futures",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Стоимость фьючерсов (значение)",
                    ),
                ),
                (
                    "total_amount_options",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Стоимость опционов (значение)",
                    ),
                ),
                (
                    "total_amount_sp",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Стоимость структ. продуктов (значение)",
                    ),
                ),
                (
                    "total_amount_portfolio",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Общая стоимость портфеля (значение)",
                    ),
                ),
                (
                    "total_amount_dfa",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Стоимость ЦФА (значение)",
                    ),
                ),
                (
                    "expected_yield",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Ожидаемая доходность",
                    ),
                ),
                (
                    "daily_yield",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Дневная доходность (значение)",
                    ),
                ),
                (
                    "daily_yield_relative",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Относительная дневная доходность",
                    ),
                ),
                (
                    "virtual_positions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Виртуальные позиции",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления данных"
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        db_column="account_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to="t_invest.tinkoffaccount",
                        to_field="account_id",
                    ),
                ),
            ],
            options={
                "verbose_name": "Портфель",
                "verbose_name_plural": "Портфели",
            },
        ),
        migrations.CreateModel(
            name="PortfolioPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_uid", models.UUIDField(verbose_name="UID позиции")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Количество бумаг",
                    ),
                ),
                (
                    "quantity_lots",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Количество лотов",
                    ),
                ),
                (
                    "blocked",
                    models.BooleanField(
                        default=False, verbose_name="Заблокировано"
                    ),
                ),
                (
                    "blocked_lots",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Заблокировано лотов",
                    ),
                ),
                (
                    "average_position_price",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Средняя цена позиции",
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Текущая цена",
                    ),
                ),
                (
                    "average_position_price_fifo",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Средняя цена по FIFO",
                    ),
                ),
                (
                    "expected_yield",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Ожидаемая доходность",
                    ),
                ),
                (
                    "expected_yield_fifo",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Ожидаемая доходность по FIFO",
                    ),
                ),
                (
                    "daily_yield",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Дневная доходность",
                    ),
                ),
                (
                    "current_nkd",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Текущий НКД",
                    ),
                ),
                (
                    "average_position_price_pt",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Средняя цена в пунктах",
                    ),
                ),
                (
                    "var_margin",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=18,
                        verbose_name="Вариационная маржа",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        db_column="instrument_uid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_positions",
                        to="data.financialinstrument",
                        verbose_name="Финансовый инструмент",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="t_invest.portfolio",
                        verbose_name="Позиции портфеля",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция",
                "verbose_name_plural": "Позиции",
                "unique_together": {("portfolio", "position_uid")},
            },
        ),
    ]
