# Generated by Django 5.2.9 on 2026-06-18 08:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("t_invest", "0002_portfolio_portfolioposition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TinkoffAccount",
            new_name="TinkoffAccaunt",
        ),
    ]
