# Generated by Django 5.2.9 on 2026-06-25 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
        ("t_invest", "0003_rename_tinkoffaccount_tinkoffaccaunt"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by_accaunt",
                        to="data.financialinstrument",
                        verbose_name="Финансовый инструмент",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_instruments",
                        to="t_invest.tinkoffaccaunt",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранный инструмент",
                "verbose_name_plural": "Избранные инструменты",
                "db_table": "favorite_instruments",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "instrument"),
                        name="unique_user_instrument",
                    )
                ],
            },
        ),
    ]
