# Generated by Django 5.2.9 on 2026-07-13 17:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
        ("t_invest", "0004_favoriteinstrument"),
    ]

    operations = [
        migrations.CreateModel(
            name="SandboxPostOrderRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.BigIntegerField(help_text="Количество лотов.")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        help_text="Цена за 1 инструмент. Игнорируется для рыночных поручений.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "direction",
                    models.IntegerField(
                        choices=[
                            (0, "Значение не указано"),
                            (1, "Покупка"),
                            (2, "Продажа"),
                        ],
                        help_text="Направление операции (BUY/SELL).",
                    ),
                ),
                (
                    "order_type",
                    models.IntegerField(
                        choices=[
                            (0, "Значение не указано"),
                            (1, "Лимитная"),
                            (2, "Рыночная"),
                            (3, "Лучшая цена"),
                        ],
                        help_text="Тип заявки (LIMIT/MARKET).",
                    ),
                ),
                (
                    "time_in_force",
                    models.IntegerField(
                        choices=[
                            (0, "Значение не определено"),
                            (1, "Заявка действует до конца торгового дня"),
                            (2, "Исполнить или отменить (частично)"),
                            (3, "Исполнить полностью или отменить"),
                        ],
                        default=1,
                        help_text="Алгоритм исполнения поручения (применяется к лимитным).",
                    ),
                ),
                (
                    "price_type",
                    models.IntegerField(
                        choices=[
                            (0, "Значение не определено"),
                            (1, "Цена в пунктах (для фьючерсов и облигаций)"),
                            (2, "Цена в валюте расчетов по инструменту"),
                        ],
                        default=0,
                        help_text="Тип цены.",
                    ),
                ),
                (
                    "confirm_margin_trade",
                    models.BooleanField(
                        default=False,
                        help_text="Согласие на выставление заявки, которая может привести к непокрытой позиции.",
                    ),
                ),
                (
                    "order_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Идентификатор запроса выставления поручения для целей идемпотентности.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_order_request",
                        to="t_invest.tinkoffaccaunt",
                        to_field="account_id",
                    ),
                ),
                (
                    "instrument_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="instrument_uid",
                        help_text="Связь с инструментом по instrument_uid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="postorder_by_instrument",
                        to="data.financialinstrument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поручение",
                "verbose_name_plural": "Поручения",
            },
        ),
        migrations.CreateModel(
            name="SandboxPostOrderResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.UUIDField(
                        help_text="Биржевой идентификатор заявки, присвоенный Тинькофф.",
                        unique=True,
                    ),
                ),
                (
                    "order_request_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Идентификатор изначального запроса (UUID для идемпотентности).",
                        null=True,
                    ),
                ),
                (
                    "instrument_uid",
                    models.UUIDField(
                        blank=True, help_text="UID финансового инструмента.", null=True
                    ),
                ),
                (
                    "figi",
                    models.CharField(
                        blank=True,
                        help_text="FIGI-идентификатор инструмента.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "execution_report_status",
                    models.IntegerField(
                        choices=[
                            (0, "Не определен"),
                            (5, "Исполнен частично"),
                            (1, "Исполнен полностью"),
                            (3, "Отменен"),
                            (4, "Новый / Выставлен"),
                            (2, "Отклонен"),
                        ],
                        default=0,
                        help_text="Текущий статус («стаканного» исполнения) заявки.",
                    ),
                ),
                (
                    "direction",
                    models.IntegerField(
                        choices=[
                            (0, "Значение не указано"),
                            (1, "Покупка"),
                            (2, "Продажа"),
                        ],
                        default=0,
                        help_text="Направление операции.",
                    ),
                ),
                (
                    "order_type",
                    models.IntegerField(
                        choices=[
                            (0, "Значение не указано"),
                            (1, "Лимитная"),
                            (2, "Рыночная"),
                            (3, "Лучшая цена"),
                        ],
                        default=0,
                        help_text="Тип заявки.",
                    ),
                ),
                (
                    "lots_requested",
                    models.BigIntegerField(help_text="Запрошено лотов."),
                ),
                (
                    "lots_executed",
                    models.BigIntegerField(help_text="Фактически исполнено лотов."),
                ),
                (
                    "initial_order_price",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Начальная цена заявки.",
                        max_digits=18,
                    ),
                ),
                (
                    "executed_order_price",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Средняя цена исполнившихся лотов.",
                        max_digits=18,
                    ),
                ),
                (
                    "total_order_amount",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Общая стоимость по заявке (с комиссией).",
                        max_digits=18,
                    ),
                ),
                (
                    "initial_commission",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Предварительная комиссия.",
                        max_digits=18,
                    ),
                ),
                (
                    "executed_commission",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Фактическая комиссия.",
                        max_digits=18,
                    ),
                ),
                (
                    "aci_value",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Накопленный купонный доход (НКД).",
                        max_digits=18,
                    ),
                ),
                (
                    "initial_security_price",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Начальная цена бумаги.",
                        max_digits=18,
                    ),
                ),
                (
                    "initial_order_price_pt",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Начальная цена заявки в пунктах (для облигаций).",
                        max_digits=18,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Дополнительное сообщение от торговой системы / текст ошибки.",
                    ),
                ),
                (
                    "response_metadata",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Сырые метаданные ответа брокера (tracking_id, server_time).",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Время сохранения ответа в вашу БД.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Время изменения."),
                ),
                (
                    "order_response",
                    models.OneToOneField(
                        help_text="Ссылка на исходный запрос поручения",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_log",
                        to="t_invest.sandboxpostorderrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на ордер (Песочница)",
                "verbose_name_plural": "Ответы на ордера (Песочница)",
            },
        ),
        migrations.AddIndex(
            model_name="sandboxpostorderrequest",
            index=models.Index(
                fields=["account_id"], name="t_invest_sa_account_2baf11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sandboxpostorderrequest",
            index=models.Index(
                fields=["instrument_id"], name="t_invest_sa_instrum_3deb36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sandboxpostorderresponse",
            index=models.Index(
                fields=["order_id"], name="t_invest_sa_order_i_97b587_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sandboxpostorderresponse",
            index=models.Index(
                fields=["instrument_uid"], name="t_invest_sa_instrum_6c234c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sandboxpostorderresponse",
            index=models.Index(
                fields=["order_request_id"], name="t_invest_sa_order_r_5dbd39_idx"
            ),
        ),
    ]
