# Generated by Django 5.2.9 on 2026-03-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradedate', models.DateField(db_index=True, verbose_name='Дата сделки')),
                ('tradetime', models.TimeField(db_index=True, verbose_name='время сделки')),
                ('secid', models.CharField(db_index=True, max_length=36, verbose_name='код инструмента')),
                ('pr_open', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='цена открытия')),
                ('pr_high', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='максимальная цена за период')),
                ('pr_low', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='минимальная цена за период')),
                ('pr_close', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='последняя цена за период')),
                ('pr_std', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='стандартное отклонение цены')),
                ('pr_vwap', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='взвешенная средняя цена')),
                ('pr_change', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='изменение цены за период, %')),
                ('vol', models.IntegerField(blank=True, null=True, verbose_name='объем в лотах')),
                ('val', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='объем в рублях')),
                ('trades', models.IntegerField(blank=True, null=True, verbose_name='количество сделок')),
                ('trades_b', models.IntegerField(blank=True, null=True, verbose_name='кол-во сделок на покупку')),
                ('trades_s', models.IntegerField(blank=True, null=True, verbose_name='кол-во сделок на покупку')),
                ('val_b', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='объем покупок в рублях')),
                ('val_s', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='объем продаж в рублях')),
                ('vol_b', models.BigIntegerField(blank=True, null=True, verbose_name='объем покупок в лотах')),
                ('vol_s', models.BigIntegerField(blank=True, null=True, verbose_name='объем продаж в лотах')),
                ('disb', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='соотношение объема покупок и продаж')),
                ('pr_vwap_b', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='средневзвешенная цена покупки')),
                ('pr_vwap_s', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='средневзвешенная цена продажи')),
                ('systime', models.DateTimeField(db_index=True, verbose_name='время системы')),
                ('sec_pr_open', models.IntegerField(blank=True, null=True, verbose_name='кол-во секунд до pr_open')),
                ('sec_pr_high', models.IntegerField(blank=True, null=True, verbose_name='кол-во секунд до pr_high')),
                ('sec_pr_low', models.IntegerField(blank=True, null=True, verbose_name='кол-во секунд до pr_low')),
                ('sec_pr_close', models.IntegerField(blank=True, null=True, verbose_name='кол-во секунд до pr_close')),
            ],
            options={
                'db_table': 'trade_data',
                'indexes': [models.Index(fields=['secid', 'tradedate', 'tradetime'], name='idx_secid_date_time'), models.Index(fields=['tradedate', 'tradetime'], name='idx_date_time'), models.Index(fields=['systime'], name='idx_systime')],
                'unique_together': {('secid', 'tradedate', 'tradetime')},
            },
        ),
    ]
