# Generated by Django 5.2.9 on 2026-05-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialInstrument",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        help_text="Уникальный идентификатор инструмента (Tinkoff UID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "figi",
                    models.CharField(
                        db_index=True,
                        help_text="Financial Instrument Global Identifier",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        db_index=True,
                        help_text="Тикер инструмента",
                        max_length=20,
                    ),
                ),
                (
                    "class_code",
                    models.CharField(
                        help_text="Класс-код (например, TQBR)", max_length=20
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название компании или инструмента",
                        max_length=255,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Тип инструмента (shares, etf, bond, currency, futures)",
                        max_length=50,
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        help_text="Биржа проведения торгов", max_length=100
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="Валюта торгов (rub, usd, eur...)",
                        max_length=10,
                    ),
                ),
                (
                    "lot",
                    models.PositiveIntegerField(
                        help_text="Размер торгового лота"
                    ),
                ),
                (
                    "min_price_increment",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Минимальный шаг цены",
                        max_digits=18,
                        max_length=20,
                    ),
                ),
                (
                    "scale",
                    models.IntegerField(
                        help_text="Количество знаков после запятой для цены"
                    ),
                ),
                (
                    "trading_status",
                    models.CharField(
                        help_text="Текущий статус торговли инструментом",
                        max_length=100,
                    ),
                ),
                (
                    "api_trade_available_flag",
                    models.BooleanField(
                        default=False,
                        help_text="Доступность торговли через API",
                    ),
                ),
                (
                    "buy_available_flag",
                    models.BooleanField(
                        default=False, help_text="Доступность покупки"
                    ),
                ),
                (
                    "sell_available_flag",
                    models.BooleanField(
                        default=False, help_text="Доступность продажи"
                    ),
                ),
                (
                    "short_enabled_flag",
                    models.BooleanField(
                        default=False, help_text="Доступность шорта"
                    ),
                ),
                (
                    "klong",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Коэффициент ставки риска для лонга",
                        max_digits=12,
                    ),
                ),
                (
                    "kshort",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Коэффициент ставки риска для шорта",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Финансовый инструмент",
                "verbose_name_plural": "Финансовые инструменты",
                "db_table": "financial_instruments",
                "indexes": [
                    models.Index(
                        fields=["ticker", "type"],
                        name="financial_i_ticker_af8a67_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TradeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tradedate",
                    models.DateField(
                        db_index=True, verbose_name="Дата сделки"
                    ),
                ),
                (
                    "tradetime",
                    models.TimeField(
                        db_index=True, verbose_name="время сделки"
                    ),
                ),
                (
                    "secid",
                    models.CharField(
                        db_index=True,
                        max_length=36,
                        verbose_name="код инструмента",
                    ),
                ),
                (
                    "pr_open",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="цена открытия",
                    ),
                ),
                (
                    "pr_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="максимальная цена за период",
                    ),
                ),
                (
                    "pr_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="минимальная цена за период",
                    ),
                ),
                (
                    "pr_close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="последняя цена за период",
                    ),
                ),
                (
                    "pr_std",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="стандартное отклонение цены",
                    ),
                ),
                (
                    "pr_vwap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="взвешенная средняя цена",
                    ),
                ),
                (
                    "pr_change",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=12,
                        null=True,
                        verbose_name="изменение цены за период, %",
                    ),
                ),
                (
                    "vol",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="объем в лотах"
                    ),
                ),
                (
                    "val",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="объем в рублях",
                    ),
                ),
                (
                    "trades",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="количество сделок"
                    ),
                ),
                (
                    "trades_b",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="кол-во сделок на покупку",
                    ),
                ),
                (
                    "trades_s",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="кол-во сделок на покупку",
                    ),
                ),
                (
                    "val_b",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="объем покупок в рублях",
                    ),
                ),
                (
                    "val_s",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="объем продаж в рублях",
                    ),
                ),
                (
                    "vol_b",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="объем покупок в лотах",
                    ),
                ),
                (
                    "vol_s",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="объем продаж в лотах",
                    ),
                ),
                (
                    "disb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="соотношение объема покупок и продаж",
                    ),
                ),
                (
                    "pr_vwap_b",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="средневзвешенная цена покупки",
                    ),
                ),
                (
                    "pr_vwap_s",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="средневзвешенная цена продажи",
                    ),
                ),
                (
                    "systime",
                    models.DateTimeField(
                        db_index=True, verbose_name="время системы"
                    ),
                ),
                (
                    "sec_pr_open",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="кол-во секунд до pr_open",
                    ),
                ),
                (
                    "sec_pr_high",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="кол-во секунд до pr_high",
                    ),
                ),
                (
                    "sec_pr_low",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="кол-во секунд до pr_low",
                    ),
                ),
                (
                    "sec_pr_close",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="кол-во секунд до pr_close",
                    ),
                ),
            ],
            options={
                "db_table": "trade_data",
                "ordering": [["tradedate", "tradetime"]],
                "indexes": [
                    models.Index(
                        fields=["secid", "tradedate", "tradetime"],
                        name="idx_secid_date_time",
                    ),
                    models.Index(
                        fields=["tradedate", "tradetime"], name="idx_date_time"
                    ),
                    models.Index(fields=["systime"], name="idx_systime"),
                ],
                "unique_together": {("secid", "tradedate", "tradetime")},
            },
        ),
    ]
