# Generated by Django 5.2.9 on 2026-07-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tradetime",
                    models.DateTimeField(verbose_name="Время торгового сигнала"),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=9, max_digits=18, verbose_name="Текущая цена"
                    ),
                ),
                (
                    "signal",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("HOLD", "Hold"), ("SELL", "Sell")],
                        max_length=4,
                        verbose_name="Сигнал",
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4, max_digits=5, verbose_name="Уверенность"
                    ),
                ),
                (
                    "prob_sell",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Вероятность продажи",
                    ),
                ),
                (
                    "prob_hold",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Вероятность удержания",
                    ),
                ),
                (
                    "prob_buy",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Вероятность покупки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Торговый сигнал",
                "verbose_name_plural": "Торговые сигналы",
                "ordering": ["tradetime"],
            },
        ),
    ]
