# Generated by Django 5.2.9 on 2026-04-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradedata',
            options={'ordering': [['tradedate', 'tradetime']]},
        ),
    ]
