# Generated by Django 5.2.9 on 2026-07-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_tradesignal"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tradesignal",
            constraint=models.UniqueConstraint(
                fields=("tradetime",), name="unique_tradetime"
            ),
        ),
    ]
